### variables

@mainManagerAccessToken =
@employeeAccessToken = 
@employeeUserId = 

@registrationToken = 

@placeSerbiaId = 
@placeSuboticaId = 

### login main manager
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dejan.zivkovic90@gmail.com",
    "password": "SomePassword123!"
}

### login employee
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dejan.zivkovic91@gmail.com",
    "password": "abc123"
}

### get main manager
GET http://localhost:3000/users/me
Authorization: Bearer {{mainManagerAccessToken}} 


### get employee
GET http://localhost:3000/users/me
Authorization: Bearer {{employeeAccessToken}} 


### create registration token
POST http://localhost:3000/users/registration-tokens
Content-Type: application/json
Authorization: Bearer {{mainManagerAccessToken}}

{
    "toUserEmail": "dejan.zivkovic91@gmail.com",
    "toUserRole": "EMPLOYEE"
}

### register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "token": "{{registrationToken}}",
    "firstName": "dejan2",
    "lastName": "zivkovic2",
    "password": "abc123"
}

### get places for manager
GET http://localhost:3000/places
Authorization: Bearer {{mainManagerAccessToken}}

### get places users: MANAGERS for manager
GET http://localhost:3000/places/users?role=MANAGER
Authorization: Bearer {{mainManagerAccessToken}}

### get places users: EMPLOYEES for manager
GET http://localhost:3000/places/users?role=EMPLOYEE
Authorization: Bearer {{mainManagerAccessToken}}

### get places for employee
GET http://localhost:3000/places
Authorization: Bearer {{employeeAccessToken}}

### get places users: MANAGERS for employee
GET http://localhost:3000/places/users?role=MANAGER
Authorization: Bearer {{employeeAccessToken}}

### get places users: EMPLOYEE for employee
GET http://localhost:3000/places/users?role=EMPLOYEE
Authorization: Bearer {{employeeAccessToken}}

### get place: Srbija for main manager
GET http://localhost:3000/places/{{placeSerbiaId}}
Authorization: Bearer {{mainManagerAccessToken}}

### get place: Srbija users: MANAGERS for main manager
GET http://localhost:3000/places/{{placeSerbiaId}}/users?role=MANAGER
Authorization: Bearer {{mainManagerAccessToken}}

### get place: Srbija users: EMPLOYEES for main manager
GET http://localhost:3000/places/{{placeSerbiaId}}/users?role=EMPLOYEES
Authorization: Bearer {{mainManagerAccessToken}}


### get place: Srbija for employee
GET http://localhost:3000/places/{{placeSerbiaId}}
Authorization: Bearer {{employeeAccessToken}}

### get place: Subotica for employee
GET http://localhost:3000/places/{{placeSuboticaId}}
Authorization: Bearer {{employeeAccessToken}}

### add employee to a place: Srbija
POST http://localhost:3000/places/{{placeSerbiaId}}/users/{{employeeUserId}}
Content-Type: application/json
Authorization: Bearer {{mainManagerAccessToken}}

### add employee to a place: Subotica
POST http://localhost:3000/places/{{placeSuboticaId}}/users/{{employeeUserId}}
Content-Type: application/json
Authorization: Bearer {{mainManagerAccessToken}}

### delete employee to a place: Srbija
DELETE  http://localhost:3000/places/{{placeSerbiaId}}/users/{{employeeUserId}}
Content-Type: application/json
Authorization: Bearer {{mainManagerAccessToken}}

### delete employee to a place: Subotica
DELETE  http://localhost:3000/places/{{placeSuboticaId}}/users/{{employeeUserId}}
Content-Type: application/json
Authorization: Bearer {{mainManagerAccessToken}}


