### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dejan.zivkovic90@gmail.com",
    "password": "SomePassword123!"
}

### login 2
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dejan.zivkovic92@gmail.com",
    "password": "abc123"
}

### me
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1ZTU3ZGNkZTg3ZTY0ODhiMTgyZjQiLCJ1c2VyUm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NjIwMDU5NDUsImV4cCI6MTc2MjAwOTU0NX0.IRYSGPTmKlHV8KK9_2O6DtlquHWDjhozXUCJB9BNxDE


### create registration token
POST http://localhost:3000/users/registration-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1ZTU3ZGNkZTg3ZTY0ODhiMTgyZjQiLCJ1c2VyUm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NjIwMTQ0MzUsImV4cCI6MTc2MjAxODAzNX0.JmxX4B9fMafrmuV9EcUa0yqCYPZV3gqOMmrRgjDHBMk

{
    "toUserEmail": "dejan.zivkovic92@gmail.com",
    "toUserRole": "EMPLOYEE"
}


### register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "token": "63d928b1-d706-4713-8da5-3ab41575b91a",
    "firstName": "dejan1",
    "lastName": "zivkovic1",
    "password": "abc123"
}

### get places
GET http://localhost:3000/places
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1ZTU3ZGNkZTg3ZTY0ODhiMTgyZjQiLCJ1c2VyUm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NjIwMjIyODYsImV4cCI6MTc2MjAyNTg4Nn0.Lo79V5ikHL1PjI0_5Jak3mH4EAGxMIf9HVyVid3XjY8

### get place
GET http://localhost:3000/places/6905e57dcde87e6488b182c6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1ZTU3ZGNkZTg3ZTY0ODhiMTgyZjQiLCJ1c2VyUm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NjIwMjIyODYsImV4cCI6MTc2MjAyNTg4Nn0.Lo79V5ikHL1PjI0_5Jak3mH4EAGxMIf9HVyVid3XjY8