### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dejan.zivkovic90@gmail.com",
    "password": "SomePassword123!"
}


### me
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlamFuLnppdmtvdmljOTBAZ21haWwuY29tIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NjE5MTgzMTUsImV4cCI6MTc2MTkxODM3NX0.s5AxyVi1v5doKJYscM1RoyQNerowsV3pngMga3h5Qis

