### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dejan.zivkovic90@gmail.com",
    "password": "SomePassword123!"
}


### me
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlamFuLnppdmtvdmljOTBAZ21haWwuY29tIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NjE5MTg0ODMsImV4cCI6MTc2MTkxODU0M30.Z3mTgntduRqz9Hg3jJhbejefuX3uBxHFZzBGooaZx9w


### get place employees
GET http://localhost:3000/places/69049048059f57fb096fa72b/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlamFuLnppdmtvdmljOTBAZ21haWwuY29tIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NjE5MjU5OTAsImV4cCI6MTc2MTkyOTU5MH0.f0Kz4WL4gslnQWXjz4bQ0VMUh5wjXzqKv6hXMb6eNOE